# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'
target 'ForHJH' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
pod "AFNetworking"
pod "pop"
pod "YYModel"
pod "SDWebImage"
pod "SVProgressHUD"
pod "SnapKit"
pod 'AMapNavi'
pod "AMapLocation"
end
