# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ForHJH' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
pod "AFNetworking"
pod "pop"
pod "YYModel"
pod "SDWebImage"
pod "SVProgressHUD"

end
